// Deterministic, non-personal product data for the marketing screenshot suite.
// Keys are the Tauri command names consumed by app/ui/src/lib/api.ts.

const liveTranscript = {
  revision: 8,
  session_id: "marketing-zoom-call",
  mode: "call",
  status: "listening",
  title: "Zoom · live transcript",
  detail: "Recording · streaming durable windows to the vagus inbox",
  active: true,
  evicted_lines: 0,
  retained_from_seq: 1,
  lines: [
    {
      seq: 1,
      speaker: "Me",
      start_sec: 3.2,
      end_sec: 7.8,
      text: "The inbox note is already open. Corti is writing this while we talk.",
    },
    {
      seq: 2,
      speaker: "Them 1",
      start_sec: 8.4,
      end_sec: 13.6,
      text: "So if the app closes, the completed transcript windows are still on disk?",
    },
    {
      seq: 3,
      speaker: "Me",
      start_sec: 14.1,
      end_sec: 20.3,
      text: "Exactly. Each bounded chunk is synced before its memory is reused.",
    },
    {
      seq: 4,
      speaker: "Them 1",
      start_sec: 22.0,
      end_sec: 28.7,
      text: "And this meeting gets tagged as Zoom without a calendar integration or a bot?",
    },
    {
      seq: 5,
      speaker: "Me",
      start_sec: 29.1,
      end_sec: 35.9,
      text: "Corti sees which process owns the microphone and carries that source into the note.",
    },
    {
      seq: 6,
      speaker: "Them 2",
      start_sec: 38.3,
      end_sec: 42.5,
      text: "Then vagus can find the decisions later by wording or by meaning.",
    },
  ],
};

const recordings = [
  {
    id: "20260818-193105-zoom",
    app: "Zoom",
    mode: "call",
    started_at: "2026-08-18T19:31:05Z",
    ended_at: "2026-08-18T19:54:11Z",
    duration_secs: 1386,
    status: "done",
    error: null,
    transcribe_secs: 5.8,
    note_path: "00-Inbox/zoom-call-2026-08-18.md",
    note_exists: true,
    audio_exists: true,
    recovery_exists: true,
    audio_bytes: 18_720_000,
    retry_pending: false,
    retry_attempts: null,
  },
  {
    id: "20260818-181944-slack",
    app: "Slack",
    mode: "call",
    started_at: "2026-08-18T18:19:44Z",
    ended_at: "2026-08-18T18:52:02Z",
    duration_secs: 1938,
    status: "done",
    error: null,
    transcribe_secs: 7.1,
    note_path: "10-Projects/demo/slack-huddle.md",
    note_exists: false,
    audio_exists: false,
    recovery_exists: false,
    audio_bytes: null,
    retry_pending: false,
    retry_attempts: null,
  },
  {
    id: "20260818-174206-google-chrome",
    app: "Google Chrome",
    mode: "webinar",
    started_at: "2026-08-18T17:42:06Z",
    ended_at: null,
    duration_secs: null,
    status: "recording",
    error: null,
    transcribe_secs: null,
    note_path: null,
    note_exists: false,
    audio_exists: true,
    recovery_exists: true,
    audio_bytes: 9_400_000,
    retry_pending: false,
    retry_attempts: null,
  },
];

const openAiDirect = {
  descriptor: {
    provider: "openai",
    transport: "openai_api",
    support_tier: "documented",
    billing_basis: "metered_estimate",
    adapter_available: true,
  },
  credential: {
    state: "ready",
    expires_at_unix_ms: null,
    source: "keychain",
  },
  models: [
    {
      provider: "openai",
      transport: "openai_api",
      support_tier: "documented",
      exact_model_id: "gpt-5.6-luna",
      account_scoped_available: true,
      region: null,
      max_context_tokens: 1_050_000,
      max_output_tokens: 128_000,
      capabilities: {
        text_input: true,
        text_output: true,
        streaming: true,
        structured_output: true,
        explicit_prefix_cache: true,
        implicit_cache_may_apply: false,
      },
      billing_basis: "metered_estimate",
      tariff_version: null,
      deprecated: false,
      benchmarked_for_live: false,
    },
  ],
  service_error: null,
};

const hostedSettings = {
  state_revision: 12,
  preferences_revision: 7,
  control: {
    process_epoch: 71,
    session_generation: 3,
    control_revision: 8,
    steering_revision: 4,
    bank_revision: 7,
    pinned_question_revision: 1,
    master_enabled: true,
    egress_acknowledged: true,
    pinned_auto_enabled: false,
    codex_experimental_approved: false,
    live: {
      enabled: false,
      revision: 2,
      selection: {
        provider: null,
        transport: null,
        model: null,
        cache_policy: { local: "reusable", provider: "off" },
      },
    },
    final_lane: {
      enabled: true,
      revision: 5,
      selection: {
        provider: "openai",
        transport: "openai_api",
        model: "gpt-5.6-luna",
        cache_policy: { local: "reusable", provider: "off" },
      },
    },
    questions: {
      enabled: true,
      revision: 4,
      selection: {
        provider: "openai",
        transport: "openai_api",
        model: "gpt-5.6-luna",
        cache_policy: { local: "reusable", provider: "off" },
      },
    },
  },
  providers: [
    {
      descriptor: {
        provider: "anthropic",
        transport: "anthropic_api",
        support_tier: "documented",
        billing_basis: "metered_estimate",
        adapter_available: true,
      },
      credential: { state: "absent" },
      models: [],
      service_error: null,
    },
    {
      descriptor: {
        provider: "anthropic",
        transport: "claude_subscription",
        support_tier: "blocked",
        billing_basis: "unknown",
        adapter_available: false,
      },
      credential: { state: "unsupported", code: "policy_blocked" },
      models: [],
      service_error: null,
    },
    {
      descriptor: {
        provider: "google",
        transport: "vertex_api",
        support_tier: "documented",
        billing_basis: "metered_estimate",
        adapter_available: true,
      },
      credential: { state: "absent" },
      models: [],
      service_error: null,
    },
    {
      descriptor: {
        provider: "openai",
        transport: "codex_app_server",
        support_tier: "experimental",
        billing_basis: "included_subscription",
        adapter_available: false,
      },
      credential: { state: "unsupported", code: "policy_blocked" },
      models: [],
      service_error: null,
    },
    openAiDirect,
  ],
  scopes: [
    {
      provider: "google",
      transport: "vertex_api",
      configured: true,
      alias: "Screenshot Vertex",
      project: "corti-screenshot-project",
      region: "global",
      quota_project: null,
    },
    {
      provider: "openai",
      transport: "openai_api",
      configured: true,
      alias: "Direct API billing",
      project: null,
      region: null,
      quota_project: null,
    },
    {
      provider: "anthropic",
      transport: "anthropic_api",
      configured: false,
      alias: null,
      project: null,
      region: null,
      quota_project: null,
    },
  ],
  default_steering: "Preserve speaker intent; correct only clear recognition errors.",
  word_bank: {
    revision: 7,
    entries: ["Corti", "Parakeet", "Vagus"],
  },
  final_deadline_seconds: 90,
  show_history_diagnostics: false,
  show_live_metrics_by_default: false,
};

export const fixtures: Record<string, unknown> = {
  get_live_transcript: liveTranscript,
  start_live_test: null,
  stop_live_test: null,
  list_recordings: recordings,
  retry_recording: null,
  open_note: null,
  reveal_audio: null,
  get_pipeline_activity: {
    stage: "transcribing",
    detail: "Zoom · transcribing locally · syncing a durable inbox window",
    recording: true,
  },
  get_config: {
    transcribe_backend: "local",
    aws_bucket: null,
    language: "en-US",
    aws_profile: null,
    aws_region: "us-east-1",
    local_threads: 8,
    local_asr_engine: "ggml",
    local_ggml_available: true,
    local_diarize_far_end: true,
    local_embedding_model: "titanet",
    aec_enabled: true,
    retention_days: 7,
    live_filing: true,
    live_buffer_minutes: 1,
    env_managed: [],
  },
  get_backends: [
    { id: "local", label: "Local · private", compiled_in: true },
    { id: "aws", label: "AWS Transcribe", compiled_in: true },
  ],
  set_config: null,
  get_hosted_settings: hostedSettings,
  patch_hosted_settings: { status: "unchanged", settings: hostedSettings },
  update_hosted_steering: { status: "unchanged", settings: hostedSettings },
  replace_hosted_word_bank: { status: "unchanged", settings: hostedSettings },
  update_hosted_provider_scope: { status: "unchanged", settings: hostedSettings },
  refresh_hosted_provider: openAiDirect,
  set_hosted_pinned_question: null,
  get_aws_status: {
    profiles: ["default"],
    selected_profile: null,
    configured_region: "us-east-1",
    profile_locked: false,
    region_locked: false,
    env_access_key_id: null,
    env_has_secret: false,
    env_session_token: false,
    env_profile: null,
    env_region: null,
    source: "AWS SDK credential chain",
  },
  get_embedding_models: [
    {
      id: "titanet",
      label: "TitaNet speaker embedding",
      present: true,
      on_disk_bytes: 24_400_000,
      download_bytes: 24_400_000,
      diarize_only: true,
    },
  ],
  get_paths: {
    recordings_dir: "~/Library/Caches/corti/recordings",
    recordings_bytes: 28_120_000,
    models_dir: "~/Library/Caches/corti/models",
    models_bytes: 804_300_000,
  },
  get_models_status: [
    {
      id: "parakeet-tdt-0.6b-v3-ggml-q8",
      label: "Parakeet TDT 0.6B v3 · Metal Q8",
      present: true,
      on_disk_bytes: 742_000_000,
      download_bytes: 742_000_000,
      diarize_only: false,
    },
    {
      id: "silero-vad",
      label: "Silero VAD",
      present: true,
      on_disk_bytes: 2_300_000,
      download_bytes: 2_300_000,
      diarize_only: false,
    },
    {
      id: "titanet",
      label: "TitaNet speaker embedding",
      present: true,
      on_disk_bytes: 24_400_000,
      download_bytes: 24_400_000,
      diarize_only: true,
    },
  ],
  reveal_path: null,
  set_models_dir: null,
  download_model: null,
};
